micronaut:
  application:
    name: grant_disbursement
datasources:
  default:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
       hbm2ddl.auto: update

flyway:
  datasources:
    default:
      locations: classpath:migrations
